language: go

env:
- GO111MODULE=on

go:
- "1.9"
- "1.10"
- "1.11"
- "tip"

git:
  depth: 1

matrix:
  allow_failures:
  - go: tip
  fast_finish: true

notifications:
  email: false

script:
- go vet ./...
- go test -v -race -coverprofile=coverage.txt -covermode=atomic
- go build

after_success:
- bash <(curl -s https://codecov.io/bash)